"""
Django settings for CyberCP project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # dotenv not available, continue without it
    pass

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Resolve order: env var -> persistent key file -> generate once and persist.
# This removes the previously hard-coded (public) fallback key, which let anyone
# forge session/CSRF/password-reset tokens on installs that never set the env var.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    _secret_key_path = os.getenv('CYBERPANEL_SECRET_KEY_FILE', '/usr/local/CyberCP/secret_key')
    try:
        with open(_secret_key_path) as _skf:
            SECRET_KEY = _skf.read().strip()
    except OSError:
        SECRET_KEY = ''

    if not SECRET_KEY:
        import secrets as _secrets
        SECRET_KEY = _secrets.token_urlsafe(50)
        try:
            _fd = os.open(_secret_key_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640)
            with os.fdopen(_fd, 'w') as _skf:
                _skf.write(SECRET_KEY)
        except FileExistsError:
            # Another worker created it first; reuse that key so all workers agree.
            try:
                with open(_secret_key_path) as _skf:
                    SECRET_KEY = _skf.read().strip() or SECRET_KEY
            except OSError:
                pass
        except OSError:
            # Could not persist (e.g. permissions); use the in-memory key for now.
            pass

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Allow configuration via environment variable, with wildcard fallback for universal compatibility
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Do not share Django's generic cookie name with other applications that may
# be served from the same panel hostname.
SESSION_COOKIE_NAME = 'cyberpanel_sessionid'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'baseTemplate',
    'firewall',
    'loginSystem',
    'packages',
    'websiteFunctions',
    'tuning',
    'serverStatus',
    'dns',
    'ftp',
    'userManagment',
    'databases',
    'mailServer',
    'serverLogs',
    'backup',
    'managePHP',
    'manageSSL',
    'api',
    'filemanager',
    'manageServices',
    'pluginHolder',
    'autoBanSecurityAlerts',
    'fail2ban',
    'emailPremium',
    'emailMarketing',
    'cloudAPI',
    'highAvailability',
    's3Backups',
    'dockerManager',
    'containerization',
    'CLManager',
    'IncBackups',
    'aiScanner',
    'webmail',
    'emailDelivery',
    #    'WebTerminal'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'CyberCP.secMiddleware.secMiddleware'
]

ROOT_URLCONF = 'CyberCP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'baseTemplate.context_processors.version_context',
                'baseTemplate.context_processors.cosmetic_context',
                'baseTemplate.context_processors.size_display_unit_context',
                'baseTemplate.context_processors.plugin_sidebar_context',
                'baseTemplate.context_processors.dns_static_context',
                'baseTemplate.context_processors.firewall_static_context',
                'baseTemplate.context_processors.notification_preferences_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'CyberCP.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cyberpanel',
        'USER': 'cyberpanel',
        'PASSWORD': '1XTy1XOV0BZPnM',
        'HOST': 'localhost',
        'PORT':''
    },
    'rootdb': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysql',
        'USER': 'root',
        'PASSWORD': '1XTy1XOV0BZPnM',
        'HOST': 'localhost',
        'PORT': '',
    },
}
DATABASE_ROUTERS = ['backup.backupRouter.backupRouter']

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static/")

STATIC_URL = '/static/'

PUBLIC_ROOT = os.path.join(BASE_DIR, 'public')

# Keep collected assets readable by LSCPD even if an upgrade is interrupted
# before the final permission repair runs.
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

LANGUAGES = (
    ('en', _('English')),
    ('cn', _('Chinese')),
    ('br', _('Bulgarian')),
    ('pt', _('Portuguese')),
    ('ja', _('Japanese')),
    ('bs', _('Bosnian')),
    ('gr', _('Greek')),
    ('ru', _('Russian')),
    ('tr', _('Turkish')),
    ('es', _('Spanish')),
    ('fr', _('French')),
    ('pl', _('Polish')),
    ('vi', _('Vietnamese')),
    ('it', _('Italian')),
    ('de', _('Deutsch')),
    ('id', _('Indonesian')),
    ('bn', _('Bangla')),
    ('nb', _('Norwegian Bokmål')),
)

MEDIA_URL = '/usr/local/CyberCP/tmp/'
MEDIA_ROOT = MEDIA_URL
DATA_UPLOAD_MAX_MEMORY_SIZE = 2147483648

# Security settings
X_FRAME_OPTIONS = 'SAMEORIGIN'

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sync INSTALLED_APPS with plugins on disk so /plugins/<name>/ and /plugins/<name>/settings/ work.
_cybercp_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if os.path.isdir(_cybercp_root):
    try:
        _plugin_source_roots = [
            '/home/cyberpanel/plugins',
            '/home/cyberpanel-plugins',
        ]
        for _src_root in _plugin_source_roots:
            try:
                if os.path.isdir(_src_root) and _src_root not in sys.path:
                    sys.path.append(_src_root)
            except Exception:
                pass

        _existing_apps = set(INSTALLED_APPS)
        for _name in os.listdir(_cybercp_root):
            if _name.startswith('.'):
                continue
            _plugin_dir = os.path.join(_cybercp_root, _name)
            if not os.path.isdir(_plugin_dir):
                continue
            if _name in _existing_apps:
                continue
            _installed_has_meta_and_urls = (
                os.path.exists(os.path.join(_plugin_dir, 'meta.xml')) and
                os.path.exists(os.path.join(_plugin_dir, 'urls.py'))
            )
            _source_has_meta_and_urls = False
            for _src_root in ('/home/cyberpanel/plugins', '/home/cyberpanel-plugins'):
                _src_dir = os.path.join(_src_root, _name)
                if not os.path.isdir(_src_dir):
                    continue
                if os.path.exists(os.path.join(_src_dir, 'meta.xml')) and os.path.exists(os.path.join(_src_dir, 'urls.py')):
                    _source_has_meta_and_urls = True
                    break
            if _installed_has_meta_and_urls or _source_has_meta_and_urls:
                INSTALLED_APPS.append(_name)
                _existing_apps.add(_name)
    except (OSError, IOError):
        pass
